In [3]:
import pandas as pd
df = pd.read_csv("vitals_raw_data.csv")

In [4]:
df

,PATNUM,SITENM,VISIT_NAME,FORM,FORML,RECPOSITION,ASMNTDN,TMPTC,VTLD,VTLTM,SUBPOS,SYS_BP,DIA_BP,PULSE,RESPRT,TEMP,TEMPLOC,OXY_SAT,LAT,LOC
0,375,Test Study,Visit 1,VTLSGN,Vital Signs,0,No,Pre-dose,16-May-15,7:25,PRONE,158.0,92.0,63.0,17.0,40.48,SKIN,98.0,RIGHT,FINGER
1,375,Test Study,Visit 1,VTLSGN,Vital Signs,1,No,Post-dose,16-May-15,10:25,SEMI-RECUMBENT,94.0,78.0,76.0,20.0,36.75,TYMPANIC MEMBRANE,99.0,LEFT,FINGER
2,375,Test Study,Screening,VTLSGN,Vital Signs,0,No,NaN,6-May-18,2:01,PRONE,117.0,62.0,66.0,15.0,29.45,ORAL CAVITY,96.0,LEFT,FINGER
3,376,Test Study,Screening,VTLSGN,Vital Signs,0,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,376,Test Study,Visit 1,VTLSGN,Vital Signs,0,No,Pre-dose,23-Oct-08,1:19,PRONE,85.0,68.0,73.0,21.0,38.25,AXILLA,93.0,RIGHT,FINGER
5,376,Test Study,Visit 1,VTLSGN,Vital Signs,0,No,Post-dose,23-Oct-08,3:19,NaN,126.0,81.0,56.0,18.0,38.08,TYMPANIC MEMBRANE,93.0,LEFT,FINGER

In [5]:
df.columns

Index(['PATNUM', 'SITENM', 'VISIT_NAME', 'FORM', 'FORML', 'RECPOSITION',
       'ASMNTDN', 'TMPTC', 'VTLD', 'VTLTM', 'SUBPOS', 'SYS_BP', 'DIA_BP',
       'PULSE', 'RESPRT', 'TEMP', 'TEMPLOC', 'OXY_SAT', 'LAT', 'LOC'],
      dtype='object')

In [6]:
df["STUDYID"] = "STUDY1"

In [7]:
df["USUBJID"] = df["STUDYID"] + "-" + df["PATNUM"].astype(str)

In [8]:
df

,PATNUM,SITENM,VISIT_NAME,FORM,FORML,RECPOSITION,ASMNTDN,TMPTC,VTLD,VTLTM,...,DIA_BP,PULSE,RESPRT,TEMP,TEMPLOC,OXY_SAT,LAT,LOC,STUDYID,USUBJID
0,375,Test Study,Visit 1,VTLSGN,Vital Signs,0,No,Pre-dose,16-May-15,7:25,...,92.0,63.0,17.0,40.48,SKIN,98.0,RIGHT,FINGER,STUDY1,STUDY1-375
1,375,Test Study,Visit 1,VTLSGN,Vital Signs,1,No,Post-dose,16-May-15,10:25,...,78.0,76.0,20.0,36.75,TYMPANIC MEMBRANE,99.0,LEFT,FINGER,STUDY1,STUDY1-375
2,375,Test Study,Screening,VTLSGN,Vital Signs,0,No,NaN,6-May-18,2:01,...,62.0,66.0,15.0,29.45,ORAL CAVITY,96.0,LEFT,FINGER,STUDY1,STUDY1-375
3,376,Test Study,Screening,VTLSGN,Vital Signs,0,Yes,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,STUDY1,STUDY1-376
4,376,Test Study,Visit 1,VTLSGN,Vital Signs,0,No,Pre-dose,23-Oct-08,1:19,...,68.0,73.0,21.0,38.25,AXILLA,93.0,RIGHT,FINGER,STUDY1,STUDY1-376
5,376,Test Study,Visit 1,VTLSGN,Vital Signs,0,No,Post-dose,23-Oct-08,3:19,...,81.0,56.0,18.0,38.08,TYMPANIC MEMBRANE,93.0,LEFT,FINGER,STUDY1,STUDY1-376

In [9]:
# Define columns to melt
value_vars = ["SYS_BP", "DIA_BP", "PULSE", "TEMP"]

In [10]:
vs = df.melt(
    id_vars=["STUDYID", "USUBJID", "SUBPOS", "TEMPLOC", "LOC"],
    value_vars=value_vars,
    var_name="RAW_TEST",
    value_name="VSORRES"
)

In [11]:
vs

,STUDYID,USUBJID,SUBPOS,TEMPLOC,LOC,RAW_TEST,VSORRES
0,STUDY1,STUDY1-375,PRONE,SKIN,FINGER,SYS_BP,158.00
1,STUDY1,STUDY1-375,SEMI-RECUMBENT,TYMPANIC MEMBRANE,FINGER,SYS_BP,94.00
2,STUDY1,STUDY1-375,PRONE,ORAL CAVITY,FINGER,SYS_BP,117.00
3,STUDY1,STUDY1-376,NaN,NaN,NaN,SYS_BP,NaN
4,STUDY1,STUDY1-376,PRONE,AXILLA,FINGER,SYS_BP,85.00
5,STUDY1,STUDY1-376,NaN,TYMPANIC MEMBRANE,FINGER,SYS_BP,126.00
6,STUDY1,STUDY1-375,PRONE,SKIN,FINGER,DIA_BP,92.00
7,STUDY1,STUDY1-375,SEMI-RECUMBENT,TYMPANIC MEMBRANE,FINGER,DIA_BP,78.00
8,STUDY1,STUDY1-375,PRONE,ORAL CAVITY,FINGER,DIA_BP,62.00
9,STUDY1,STUDY1-376,NaN,NaN,NaN,DIA_BP,NaN
10,STUDY1,STUDY1-376,PRONE,AXILLA,FINGER,DIA_BP,68.00
11,STUDY1,STUDY1-376,NaN,TYMPANIC MEMBRANE,FINGER,DIA_BP,81.00
12,STUDY1,STUDY1-375,PRONE,SKIN,FINGER,PULSE,63.00
13,STUDY1,STUDY1-375,SEMI-RECUMBENT,TYMPANIC MEMBRANE,FINGER,PULSE,76.00
14,STUDY1,STUDY1-375,PRONE,ORAL CAVITY,FINGER,PULSE,66.00
15,STUDY1,STUDY1-376,NaN,NaN,NaN,PULSE,NaN
16,STUDY1,STUDY1-376,PRONE,AXILLA,FINGER,PULSE,73.00
17,STUDY1,STUDY1-376,NaN,TYMPANIC MEMBRANE,FINGER,PULSE,56.00
18,STUDY1,STUDY1-375,PRONE,SKIN,FINGER,TEMP,40.48
19,STUDY1,STUDY1-375,SEMI-RECUMBENT,TYMPANIC MEMBRANE,FINGER,TEMP,36.75
20,STUDY1,STUDY1-375,PRONE,ORAL CAVITY,FINGER,TEMP,29.45
21,STUDY1,STUDY1-376,NaN,NaN,NaN,TEMP,NaN
22,STUDY1,STUDY1-376,PRONE,AXILLA,FINGER,TEMP,38.25
23,STUDY1,STUDY1-376,NaN,TYMPANIC MEMBRANE,FINGER,TEMP,38.08

In [12]:
vs = vs.dropna(subset=["VSORRES"])

In [13]:
# Map RAW_TEST → VSTESTCD
test_map = {
    "SYS_BP": "SYSBP",
    "DIA_BP": "DIABP",
    "PULSE": "PULSE",
    "TEMP": "TEMP"
}
vs["VSTESTCD"] = vs["RAW_TEST"].map(test_map)

C:\Users\amar\AppData\Local\Temp\ipykernel_28696\94104577.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vs["VSTESTCD"] = vs["RAW_TEST"].map(test_map)

In [14]:
vs

,STUDYID,USUBJID,SUBPOS,TEMPLOC,LOC,RAW_TEST,VSORRES,VSTESTCD
0,STUDY1,STUDY1-375,PRONE,SKIN,FINGER,SYS_BP,158.00,SYSBP
1,STUDY1,STUDY1-375,SEMI-RECUMBENT,TYMPANIC MEMBRANE,FINGER,SYS_BP,94.00,SYSBP
2,STUDY1,STUDY1-375,PRONE,ORAL CAVITY,FINGER,SYS_BP,117.00,SYSBP
4,STUDY1,STUDY1-376,PRONE,AXILLA,FINGER,SYS_BP,85.00,SYSBP
5,STUDY1,STUDY1-376,NaN,TYMPANIC MEMBRANE,FINGER,SYS_BP,126.00,SYSBP
6,STUDY1,STUDY1-375,PRONE,SKIN,FINGER,DIA_BP,92.00,DIABP
7,STUDY1,STUDY1-375,SEMI-RECUMBENT,TYMPANIC MEMBRANE,FINGER,DIA_BP,78.00,DIABP
8,STUDY1,STUDY1-375,PRONE,ORAL CAVITY,FINGER,DIA_BP,62.00,DIABP
10,STUDY1,STUDY1-376,PRONE,AXILLA,FINGER,DIA_BP,68.00,DIABP
11,STUDY1,STUDY1-376,NaN,TYMPANIC MEMBRANE,FINGER,DIA_BP,81.00,DIABP
12,STUDY1,STUDY1-375,PRONE,SKIN,FINGER,PULSE,63.00,PULSE
13,STUDY1,STUDY1-375,SEMI-RECUMBENT,TYMPANIC MEMBRANE,FINGER,PULSE,76.00,PULSE
14,STUDY1,STUDY1-375,PRONE,ORAL CAVITY,FINGER,PULSE,66.00,PULSE
16,STUDY1,STUDY1-376,PRONE,AXILLA,FINGER,PULSE,73.00,PULSE
17,STUDY1,STUDY1-376,NaN,TYMPANIC MEMBRANE,FINGER,PULSE,56.00,PULSE
18,STUDY1,STUDY1-375,PRONE,SKIN,FINGER,TEMP,40.48,TEMP
19,STUDY1,STUDY1-375,SEMI-RECUMBENT,TYMPANIC MEMBRANE,FINGER,TEMP,36.75,TEMP
20,STUDY1,STUDY1-375,PRONE,ORAL CAVITY,FINGER,TEMP,29.45,TEMP
22,STUDY1,STUDY1-376,PRONE,AXILLA,FINGER,TEMP,38.25,TEMP
23,STUDY1,STUDY1-376,NaN,TYMPANIC MEMBRANE,FINGER,TEMP,38.08,TEMP

In [15]:
unit_map = {
    "SYSBP": "mmHg",
    "DIABP": "mmHg",
    "PULSE": "beats/min",
    "TEMP": "C"
}
vs["VSORRESU"] = vs["VSTESTCD"].map(unit_map)

C:\Users\amar\AppData\Local\Temp\ipykernel_28696\2572194689.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vs["VSORRESU"] = vs["VSTESTCD"].map(unit_map)

In [16]:
vs

,STUDYID,USUBJID,SUBPOS,TEMPLOC,LOC,RAW_TEST,VSORRES,VSTESTCD,VSORRESU
0,STUDY1,STUDY1-375,PRONE,SKIN,FINGER,SYS_BP,158.00,SYSBP,mmHg
1,STUDY1,STUDY1-375,SEMI-RECUMBENT,TYMPANIC MEMBRANE,FINGER,SYS_BP,94.00,SYSBP,mmHg
2,STUDY1,STUDY1-375,PRONE,ORAL CAVITY,FINGER,SYS_BP,117.00,SYSBP,mmHg
4,STUDY1,STUDY1-376,PRONE,AXILLA,FINGER,SYS_BP,85.00,SYSBP,mmHg
5,STUDY1,STUDY1-376,NaN,TYMPANIC MEMBRANE,FINGER,SYS_BP,126.00,SYSBP,mmHg
6,STUDY1,STUDY1-375,PRONE,SKIN,FINGER,DIA_BP,92.00,DIABP,mmHg
7,STUDY1,STUDY1-375,SEMI-RECUMBENT,TYMPANIC MEMBRANE,FINGER,DIA_BP,78.00,DIABP,mmHg
8,STUDY1,STUDY1-375,PRONE,ORAL CAVITY,FINGER,DIA_BP,62.00,DIABP,mmHg
10,STUDY1,STUDY1-376,PRONE,AXILLA,FINGER,DIA_BP,68.00,DIABP,mmHg
11,STUDY1,STUDY1-376,NaN,TYMPANIC MEMBRANE,FINGER,DIA_BP,81.00,DIABP,mmHg
12,STUDY1,STUDY1-375,PRONE,SKIN,FINGER,PULSE,63.00,PULSE,beats/min
13,STUDY1,STUDY1-375,SEMI-RECUMBENT,TYMPANIC MEMBRANE,FINGER,PULSE,76.00,PULSE,beats/min
14,STUDY1,STUDY1-375,PRONE,ORAL CAVITY,FINGER,PULSE,66.00,PULSE,beats/min
16,STUDY1,STUDY1-376,PRONE,AXILLA,FINGER,PULSE,73.00,PULSE,beats/min
17,STUDY1,STUDY1-376,NaN,TYMPANIC MEMBRANE,FINGER,PULSE,56.00,PULSE,beats/min
18,STUDY1,STUDY1-375,PRONE,SKIN,FINGER,TEMP,40.48,TEMP,C
19,STUDY1,STUDY1-375,SEMI-RECUMBENT,TYMPANIC MEMBRANE,FINGER,TEMP,36.75,TEMP,C
20,STUDY1,STUDY1-375,PRONE,ORAL CAVITY,FINGER,TEMP,29.45,TEMP,C
22,STUDY1,STUDY1-376,PRONE,AXILLA,FINGER,TEMP,38.25,TEMP,C
23,STUDY1,STUDY1-376,NaN,TYMPANIC MEMBRANE,FINGER,TEMP,38.08,TEMP,C

In [17]:
# Standard result
vs["VSSTRESC"] = vs["VSORRES"]
vs["VSSTRESU"] = vs["VSORRESU"]

# Position
vs["VSPOS"] = vs["SUBPOS"]

C:\Users\amar\AppData\Local\Temp\ipykernel_28696\3151413559.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vs["VSSTRESC"] = vs["VSORRES"]
C:\Users\amar\AppData\Local\Temp\ipykernel_28696\3151413559.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vs["VSSTRESU"] = vs["VSORRESU"]
C:\Users\amar\AppData\Local\Temp\ipykernel_28696\3151413559.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vs["VSPOS"] = vs["SUBPOS"]

In [18]:
vs

,STUDYID,USUBJID,SUBPOS,TEMPLOC,LOC,RAW_TEST,VSORRES,VSTESTCD,VSORRESU,VSSTRESC,VSSTRESU,VSPOS
0,STUDY1,STUDY1-375,PRONE,SKIN,FINGER,SYS_BP,158.00,SYSBP,mmHg,158.00,mmHg,PRONE
1,STUDY1,STUDY1-375,SEMI-RECUMBENT,TYMPANIC MEMBRANE,FINGER,SYS_BP,94.00,SYSBP,mmHg,94.00,mmHg,SEMI-RECUMBENT
2,STUDY1,STUDY1-375,PRONE,ORAL CAVITY,FINGER,SYS_BP,117.00,SYSBP,mmHg,117.00,mmHg,PRONE
4,STUDY1,STUDY1-376,PRONE,AXILLA,FINGER,SYS_BP,85.00,SYSBP,mmHg,85.00,mmHg,PRONE
5,STUDY1,STUDY1-376,NaN,TYMPANIC MEMBRANE,FINGER,SYS_BP,126.00,SYSBP,mmHg,126.00,mmHg,NaN
6,STUDY1,STUDY1-375,PRONE,SKIN,FINGER,DIA_BP,92.00,DIABP,mmHg,92.00,mmHg,PRONE
7,STUDY1,STUDY1-375,SEMI-RECUMBENT,TYMPANIC MEMBRANE,FINGER,DIA_BP,78.00,DIABP,mmHg,78.00,mmHg,SEMI-RECUMBENT
8,STUDY1,STUDY1-375,PRONE,ORAL CAVITY,FINGER,DIA_BP,62.00,DIABP,mmHg,62.00,mmHg,PRONE
10,STUDY1,STUDY1-376,PRONE,AXILLA,FINGER,DIA_BP,68.00,DIABP,mmHg,68.00,mmHg,PRONE
11,STUDY1,STUDY1-376,NaN,TYMPANIC MEMBRANE,FINGER,DIA_BP,81.00,DIABP,mmHg,81.00,mmHg,NaN
12,STUDY1,STUDY1-375,PRONE,SKIN,FINGER,PULSE,63.00,PULSE,beats/min,63.00,beats/min,PRONE
13,STUDY1,STUDY1-375,SEMI-RECUMBENT,TYMPANIC MEMBRANE,FINGER,PULSE,76.00,PULSE,beats/min,76.00,beats/min,SEMI-RECUMBENT
14,STUDY1,STUDY1-375,PRONE,ORAL CAVITY,FINGER,PULSE,66.00,PULSE,beats/min,66.00,beats/min,PRONE
16,STUDY1,STUDY1-376,PRONE,AXILLA,FINGER,PULSE,73.00,PULSE,beats/min,73.00,beats/min,PRONE
17,STUDY1,STUDY1-376,NaN,TYMPANIC MEMBRANE,FINGER,PULSE,56.00,PULSE,beats/min,56.00,beats/min,NaN
18,STUDY1,STUDY1-375,PRONE,SKIN,FINGER,TEMP,40.48,TEMP,C,40.48,C,PRONE
19,STUDY1,STUDY1-375,SEMI-RECUMBENT,TYMPANIC MEMBRANE,FINGER,TEMP,36.75,TEMP,C,36.75,C,SEMI-RECUMBENT
20,STUDY1,STUDY1-375,PRONE,ORAL CAVITY,FINGER,TEMP,29.45,TEMP,C,29.45,C,PRONE
22,STUDY1,STUDY1-376,PRONE,AXILLA,FINGER,TEMP,38.25,TEMP,C,38.25,C,PRONE
23,STUDY1,STUDY1-376,NaN,TYMPANIC MEMBRANE,FINGER,TEMP,38.08,TEMP,C,38.08,C,NaN

In [19]:
vs["VSLOC"] = vs.apply(
    lambda x: x["TEMPLOC"] if x["VSTESTCD"] == "TEMP" else x["LOC"],
    axis=1
)

C:\Users\amar\AppData\Local\Temp\ipykernel_28696\1531749805.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vs["VSLOC"] = vs.apply(

In [20]:
vs

,STUDYID,USUBJID,SUBPOS,TEMPLOC,LOC,RAW_TEST,VSORRES,VSTESTCD,VSORRESU,VSSTRESC,VSSTRESU,VSPOS,VSLOC
0,STUDY1,STUDY1-375,PRONE,SKIN,FINGER,SYS_BP,158.00,SYSBP,mmHg,158.00,mmHg,PRONE,FINGER
1,STUDY1,STUDY1-375,SEMI-RECUMBENT,TYMPANIC MEMBRANE,FINGER,SYS_BP,94.00,SYSBP,mmHg,94.00,mmHg,SEMI-RECUMBENT,FINGER
2,STUDY1,STUDY1-375,PRONE,ORAL CAVITY,FINGER,SYS_BP,117.00,SYSBP,mmHg,117.00,mmHg,PRONE,FINGER
4,STUDY1,STUDY1-376,PRONE,AXILLA,FINGER,SYS_BP,85.00,SYSBP,mmHg,85.00,mmHg,PRONE,FINGER
5,STUDY1,STUDY1-376,NaN,TYMPANIC MEMBRANE,FINGER,SYS_BP,126.00,SYSBP,mmHg,126.00,mmHg,NaN,FINGER
6,STUDY1,STUDY1-375,PRONE,SKIN,FINGER,DIA_BP,92.00,DIABP,mmHg,92.00,mmHg,PRONE,FINGER
7,STUDY1,STUDY1-375,SEMI-RECUMBENT,TYMPANIC MEMBRANE,FINGER,DIA_BP,78.00,DIABP,mmHg,78.00,mmHg,SEMI-RECUMBENT,FINGER
8,STUDY1,STUDY1-375,PRONE,ORAL CAVITY,FINGER,DIA_BP,62.00,DIABP,mmHg,62.00,mmHg,PRONE,FINGER
10,STUDY1,STUDY1-376,PRONE,AXILLA,FINGER,DIA_BP,68.00,DIABP,mmHg,68.00,mmHg,PRONE,FINGER
11,STUDY1,STUDY1-376,NaN,TYMPANIC MEMBRANE,FINGER,DIA_BP,81.00,DIABP,mmHg,81.00,mmHg,NaN,FINGER
12,STUDY1,STUDY1-375,PRONE,SKIN,FINGER,PULSE,63.00,PULSE,beats/min,63.00,beats/min,PRONE,FINGER
13,STUDY1,STUDY1-375,SEMI-RECUMBENT,TYMPANIC MEMBRANE,FINGER,PULSE,76.00,PULSE,beats/min,76.00,beats/min,SEMI-RECUMBENT,FINGER
14,STUDY1,STUDY1-375,PRONE,ORAL CAVITY,FINGER,PULSE,66.00,PULSE,beats/min,66.00,beats/min,PRONE,FINGER
16,STUDY1,STUDY1-376,PRONE,AXILLA,FINGER,PULSE,73.00,PULSE,beats/min,73.00,beats/min,PRONE,FINGER
17,STUDY1,STUDY1-376,NaN,TYMPANIC MEMBRANE,FINGER,PULSE,56.00,PULSE,beats/min,56.00,beats/min,NaN,FINGER
18,STUDY1,STUDY1-375,PRONE,SKIN,FINGER,TEMP,40.48,TEMP,C,40.48,C,PRONE,SKIN
19,STUDY1,STUDY1-375,SEMI-RECUMBENT,TYMPANIC MEMBRANE,FINGER,TEMP,36.75,TEMP,C,36.75,C,SEMI-RECUMBENT,TYMPANIC MEMBRANE
20,STUDY1,STUDY1-375,PRONE,ORAL CAVITY,FINGER,TEMP,29.45,TEMP,C,29.45,C,PRONE,ORAL CAVITY
22,STUDY1,STUDY1-376,PRONE,AXILLA,FINGER,TEMP,38.25,TEMP,C,38.25,C,PRONE,AXILLA
23,STUDY1,STUDY1-376,NaN,TYMPANIC MEMBRANE,FINGER,TEMP,38.08,TEMP,C,38.08,C,NaN,TYMPANIC MEMBRANE

In [21]:
vs = vs[
    [
        "STUDYID",
        "USUBJID",
        "VSTESTCD",
        "VSORRES",
        "VSORRESU",
        "VSSTRESC",
        "VSSTRESU",
        "VSPOS",
        "VSLOC",
    ]
]

In [22]:
vs

,STUDYID,USUBJID,VSTESTCD,VSORRES,VSORRESU,VSSTRESC,VSSTRESU,VSPOS,VSLOC
0,STUDY1,STUDY1-375,SYSBP,158.00,mmHg,158.00,mmHg,PRONE,FINGER
1,STUDY1,STUDY1-375,SYSBP,94.00,mmHg,94.00,mmHg,SEMI-RECUMBENT,FINGER
2,STUDY1,STUDY1-375,SYSBP,117.00,mmHg,117.00,mmHg,PRONE,FINGER
4,STUDY1,STUDY1-376,SYSBP,85.00,mmHg,85.00,mmHg,PRONE,FINGER
5,STUDY1,STUDY1-376,SYSBP,126.00,mmHg,126.00,mmHg,NaN,FINGER
6,STUDY1,STUDY1-375,DIABP,92.00,mmHg,92.00,mmHg,PRONE,FINGER
7,STUDY1,STUDY1-375,DIABP,78.00,mmHg,78.00,mmHg,SEMI-RECUMBENT,FINGER
8,STUDY1,STUDY1-375,DIABP,62.00,mmHg,62.00,mmHg,PRONE,FINGER
10,STUDY1,STUDY1-376,DIABP,68.00,mmHg,68.00,mmHg,PRONE,FINGER
11,STUDY1,STUDY1-376,DIABP,81.00,mmHg,81.00,mmHg,NaN,FINGER
12,STUDY1,STUDY1-375,PULSE,63.00,beats/min,63.00,beats/min,PRONE,FINGER
13,STUDY1,STUDY1-375,PULSE,76.00,beats/min,76.00,beats/min,SEMI-RECUMBENT,FINGER
14,STUDY1,STUDY1-375,PULSE,66.00,beats/min,66.00,beats/min,PRONE,FINGER
16,STUDY1,STUDY1-376,PULSE,73.00,beats/min,73.00,beats/min,PRONE,FINGER
17,STUDY1,STUDY1-376,PULSE,56.00,beats/min,56.00,beats/min,NaN,FINGER
18,STUDY1,STUDY1-375,TEMP,40.48,C,40.48,C,PRONE,SKIN
19,STUDY1,STUDY1-375,TEMP,36.75,C,36.75,C,SEMI-RECUMBENT,TYMPANIC MEMBRANE
20,STUDY1,STUDY1-375,TEMP,29.45,C,29.45,C,PRONE,ORAL CAVITY
22,STUDY1,STUDY1-376,TEMP,38.25,C,38.25,C,PRONE,AXILLA
23,STUDY1,STUDY1-376,TEMP,38.08,C,38.08,C,NaN,TYMPANIC MEMBRANE

In [23]:
vs.to_csv("vs.csv", index=False)

In [25]:
!Rscript -e "write.csv(pharmaversesdtm::vs, 'vs_golden.csv', row.names=FALSE)"

In [27]:
golden=pd.read_csv("vs_golden.csv")

In [28]:
print("Your shape:", vs.shape)
print("Golden shape:", golden.shape)

print("\nColumn difference:")
print(set(vs.columns) ^ set(golden.columns))

Your shape: (20, 9)
Golden shape: (29643, 24)

Column difference:
{'VSTEST', 'VSDTC', 'VSTPTNUM', 'VISITDY', 'DOMAIN', 'VSBLFL', 'VSSEQ', 'VSDY', 'VSTPTREF', 'VSSTRESN', 'VSELTM', 'VISITNUM', 'VSTPT', 'VSSTAT', 'VISIT'}

In [30]:
print("Common columns:", list(set(vs.columns) & set(golden.columns)))

Common columns: ['VSLOC', 'VSORRES', 'VSORRESU', 'STUDYID', 'VSTESTCD', 'VSPOS', 'USUBJID', 'VSSTRESU', 'VSSTRESC']

In [31]:
import subprocess

print("Running R script...")
subprocess.run(["Rscript", "generated.R"])

print("Done! vs.csv created.")

Running R script...
Done! vs.csv created.

In [34]:
import os
os.makedirs("output", exist_ok=True)

In [35]:
import subprocess
subprocess.run(["Rscript", "generated.R"])

CompletedProcess(args=['Rscript', 'generated.R'], returncode=0)

In [36]:
import subprocess
import os

os.makedirs("output", exist_ok=True)

subprocess.run(["Rscript", "generated.R"])

CompletedProcess(args=['Rscript', 'generated.R'], returncode=0)

In [ ]:

vs = pd.read_csv("output/vs.csv")

print(vs.head())
print(vs.isna().sum())

  STUDYID     USUBJID VSTESTCD  VSORRES VSORRESU  VSSTRESC VSSTRESU  \
0  STUDY1  STUDY1-375     TEMP    40.48        C     40.48        C
1  STUDY1  STUDY1-375     TEMP    36.75        C     36.75        C
2  STUDY1  STUDY1-375     TEMP    29.45        C     29.45        C
3  STUDY1  STUDY1-376     TEMP    38.25        C     38.25        C
4  STUDY1  STUDY1-376     TEMP    38.08        C     38.08        C

            VSPOS              VSLOC
0           PRONE               SKIN
1  SEMI-RECUMBENT  TYMPANIC MEMBRANE
2           PRONE        ORAL CAVITY
3           PRONE             AXILLA
4             NaN  TYMPANIC MEMBRANE
STUDYID     0
USUBJID     0
VSTESTCD    0
VSORRES     0
VSORRESU    0
VSSTRESC    0
VSSTRESU    0
VSPOS       4
VSLOC       0
dtype: int64

In [ ]:
#validation

In [41]:
required_cols = ["STUDYID","USUBJID","VSTESTCD","VSORRES","VSORRESU"]
missing = [c for c in required_cols if c not in vs.columns]
print("Missing:", missing)

Missing: []

In [43]:

ct = pd.read_csv("sdtm_ct.csv")   # or correct path
valid_tests = set(ct[ct["codelist_code"]=="C66741"]["term_value"])
invalid = vs[~vs["VSTESTCD"].isin(valid_tests)]

print("Invalid VSTESTCD:", invalid["VSTESTCD"].unique())

Invalid VSTESTCD: []

In [44]:
set(vs.columns) == set(golden.columns)

False

In [45]:
valid_units = set(ct[ct["codelist_code"]=="C66770"]["term_value"])
valid_pos   = set(ct[ct["codelist_code"]=="C71148"]["term_value"])
valid_loc   = set(ct[ct["codelist_code"]=="C74456"]["term_value"])

In [46]:
invalid_units = vs[~vs["VSORRESU"].isin(valid_units)]

print("Invalid Units:", invalid_units["VSORRESU"].unique())

Invalid Units: []

In [47]:
invalid_pos = vs[~vs["VSPOS"].isin(valid_pos)]

print("Invalid Positions:", invalid_pos["VSPOS"].unique())

Invalid Positions: [nan]

In [48]:
invalid_loc = vs[~vs["VSLOC"].isin(valid_loc)]

print("Invalid Locations:", invalid_loc["VSLOC"].unique())

Invalid Locations: []

In [49]:
print("---- Validation Summary ----")

print("Units OK:", invalid_units.empty)
print("Position OK:", invalid_pos.empty)
print("Location OK:", invalid_loc.empty)

---- Validation Summary ----
Units OK: True
Position OK: False
Location OK: True

In [50]:
import pandas as pd
vs = pd.read_csv("output/vs.csv")
vs.head()

,STUDYID,USUBJID,VSTESTCD,VSORRES,VSORRESU,VSSTRESC,VSSTRESU,VSPOS,VSLOC
0,STUDY1,STUDY1-375,TEMP,40.48,C,40.48,C,PRONE,SKIN
1,STUDY1,STUDY1-375,TEMP,36.75,C,36.75,C,SEMI-RECUMBENT,TYMPANIC MEMBRANE
2,STUDY1,STUDY1-375,TEMP,29.45,C,29.45,C,PRONE,ORAL CAVITY
3,STUDY1,STUDY1-376,TEMP,38.25,C,38.25,C,PRONE,AXILLA
4,STUDY1,STUDY1-376,TEMP,38.08,C,38.08,C,NaN,TYMPANIC MEMBRANE